export const DEPS = [
  { id: 1, name: "log4j", version: "2.14.1", latest: "2.17.2", sev: "CRITICAL", score: 10.0, cves: ["CVE-2021-44228", "CVE-2021-45046"], vulns: 2, desc: "Log4Shell — Remote Code Execution via JNDI injection in log messages. Allows unauthenticated attackers to execute arbitrary code on the server.", updated: "2021-11-15", maint: "Active", origin: ["react-ecommerce-app", "spring-boot", "log4j"], fix: "mvn versions:use-latest-releases -Dincludes=org.apache.logging.log4j:*", fixv: "2.17.2", alts: [{ name: "logback", cmd: "mvn dependency:exclude log4j" }, { name: "slf4j", cmd: "mvn add slf4j-simple" }], effort: "Hard", sz: 28, col: "#ef4444" },
  { id: 2, name: "axios", version: "0.21.0", latest: "1.6.2", sev: "CRITICAL", score: 8.8, cves: ["CVE-2021-3749"], vulns: 1, desc: "Server-Side Request Forgery (SSRF) — allows attackers to send forged requests to internal resources via unsafe redirect following.", updated: "2021-08-31", maint: "Active", origin: ["react-ecommerce-app", "axios"], fix: "npm install axios@1.6.2", fixv: "1.6.2", alts: [{ name: "fetch API", cmd: "// Use native fetch (built-in)" }, { name: "ky", cmd: "npm install ky" }], effort: "Easy", sz: 30, col: "#ef4444" },
  { id: 3, name: "lodash", version: "4.17.15", latest: "4.17.21", sev: "CRITICAL", score: 7.4, cves: ["CVE-2020-8203"], vulns: 1, desc: "Prototype Pollution in zipObjectDeep — attacker can add/modify Object.prototype properties, leading to application takeover.", updated: "2020-04-27", maint: "Inactive", origin: ["react-ecommerce-app", "webpack", "lodash"], fix: "npm install lodash@4.17.21", fixv: "4.17.21", alts: [{ name: "lodash-es", cmd: "npm install lodash-es" }, { name: "remeda", cmd: "npm install remeda" }], effort: "Easy", sz: 26, col: "#ef4444" },
  { id: 4, name: "express", version: "4.17.0", latest: "4.18.2", sev: "HIGH", score: 7.5, cves: ["CVE-2022-24999"], vulns: 1, desc: "Open Redirect via the qs module allows attackers to redirect users to malicious external sites with crafted query strings.", updated: "2022-11-26", maint: "Active", origin: ["react-ecommerce-app", "express"], fix: "npm install express@4.18.2", fixv: "4.18.2", alts: [{ name: "fastify", cmd: "npm install fastify" }, { name: "koa", cmd: "npm install koa" }], effort: "Medium", sz: 24, col: "#f97316" },
  { id: 5, name: "minimist", version: "1.2.5", latest: "1.2.8", sev: "HIGH", score: 7.3, cves: ["CVE-2021-44906"], vulns: 1, desc: "Prototype Pollution via __proto__ keys in CLI argument parsing. Attacker-controlled input can corrupt the global Object prototype.", updated: "2022-03-17", maint: "Active", origin: ["react-ecommerce-app", "webpack-cli", "minimist"], fix: "npm install minimist@1.2.8", fixv: "1.2.8", alts: [{ name: "yargs", cmd: "npm install yargs" }, { name: "commander", cmd: "npm install commander" }], effort: "Easy", sz: 14, col: "#f97316" },
  { id: 6, name: "node-fetch", version: "2.6.0", latest: "3.3.2", sev: "HIGH", score: 8.2, cves: ["CVE-2022-0235"], vulns: 1, desc: "Sensitive information exposure via URL redirection to arbitrary protocol handlers, leaking credentials in the Referer header.", updated: "2022-01-24", maint: "Active", origin: ["react-ecommerce-app", "node-fetch"], fix: "npm install node-fetch@3.3.2", fixv: "3.3.2", alts: [{ name: "got", cmd: "npm install got" }, { name: "undici", cmd: "npm install undici" }], effort: "Medium", sz: 18, col: "#f97316" },
  { id: 7, name: "tar", version: "4.4.8", latest: "6.2.0", sev: "HIGH", score: 7.5, cves: ["CVE-2021-37701", "CVE-2021-37712"], vulns: 2, desc: "Arbitrary file creation/overwrite via symlink attack during extraction — path traversal can overwrite system files.", updated: "2021-08-31", maint: "Active", origin: ["react-ecommerce-app", "npm", "tar"], fix: "npm install tar@6.2.0", fixv: "6.2.0", alts: [{ name: "archiver", cmd: "npm install archiver" }], effort: "Medium", sz: 16, col: "#f97316" },
  { id: 8, name: "path-parse", version: "1.0.6", latest: "1.0.7", sev: "HIGH", score: 7.5, cves: ["CVE-2021-23343"], vulns: 1, desc: "ReDoS in posix.parse() via crafted input causes catastrophic regex backtracking.", updated: "2021-05-04", maint: "Inactive", origin: ["react-ecommerce-app", "resolve", "path-parse"], fix: "npm install path-parse@1.0.7", fixv: "1.0.7", alts: [], effort: "Easy", sz: 12, col: "#f97316" },
  { id: 9, name: "moment", version: "2.24.0", latest: "2.30.1", sev: "MEDIUM", score: 5.3, cves: ["CVE-2022-24785"], vulns: 1, desc: "Path Traversal when parsing user-supplied locale strings. Maintainers consider this library legacy.", updated: "2022-04-04", maint: "Inactive", origin: ["react-ecommerce-app", "moment"], fix: "npm install moment@2.30.1", fixv: "2.30.1", alts: [{ name: "date-fns", cmd: "npm install date-fns" }, { name: "dayjs", cmd: "npm install dayjs" }], effort: "Medium", sz: 20, col: "#eab308" },
  { id: 10, name: "serialize-javascript", version: "2.1.1", latest: "6.0.1", sev: "MEDIUM", score: 5.6, cves: ["CVE-2020-7660"], vulns: 1, desc: "RCE if untrusted input is passed to serialize() — regex injection via string properties.", updated: "2020-05-11", maint: "Active", origin: ["react-ecommerce-app", "webpack", "serialize-javascript"], fix: "npm install serialize-javascript@6.0.1", fixv: "6.0.1", alts: [], effort: "Easy", sz: 11, col: "#eab308" },
  { id: 24, name: "react", version: "18.2.0", latest: "18.2.0", sev: "SAFE", score: 0, cves: [], vulns: 0, desc: "No known vulnerabilities. Core UI library for building user interfaces.", updated: "2023-06-14", maint: "Active", origin: ["react-ecommerce-app", "react"], fix: "", fixv: "18.2.0", alts: [], effort: "Easy", sz: 32, col: "#14b8a6" },
  { id: 25, name: "react-dom", version: "18.2.0", latest: "18.2.0", sev: "SAFE", score: 0, cves: [], vulns: 0, desc: "No known vulnerabilities. DOM rendering layer for React.", updated: "2023-06-14", maint: "Active", origin: ["react-ecommerce-app", "react-dom"], fix: "", fixv: "18.2.0", alts: [], effort: "Easy", sz: 28, col: "#14b8a6" },
  { id: 26, name: "typescript", version: "5.2.2", latest: "5.3.3", sev: "SAFE", score: 0, cves: [], vulns: 0, desc: "No known vulnerabilities. TypeScript adds static typing to JavaScript.", updated: "2023-11-20", maint: "Active", origin: ["react-ecommerce-app", "typescript"], fix: "", fixv: "5.3.3", alts: [], effort: "Easy", sz: 22, col: "#14b8a6" },
];

export const PIPE = [
  { icon: "⬡", label: "Repo Cloner", desc: "Downloading codebase from remote" },
  { icon: "⬡", label: "Manifest Scanner", desc: "Reading package.json / requirements.txt" },
  { icon: "⬡", label: "Dependency Tree Builder", desc: "Mapping direct + transitive dependencies" },
  { icon: "⬡", label: "Vulnerability Checker", desc: "Cross-referencing NVD + OSV databases" },
  { icon: "⬡", label: "Graph Engine", desc: "Constructing visual dependency map" },
  { icon: "⬡", label: "Risk Scoring Engine", desc: "Scoring by Severity, Depth, Age & Maintainer Health" },
  { icon: "⬡", label: "Origin Tracer", desc: "Tracing how vulnerable libs entered the project" },
  { icon: "⬡", label: "Priority Ranker", desc: "Ranking remediation by impact" },
];

export const SEV = {
  CRITICAL: { color: "text-red-500", border: "border-red-500/30", bg: "bg-red-500/10", hex: "#ef4444" },
  HIGH: { color: "text-orange-500", border: "border-orange-500/30", bg: "bg-orange-500/10", hex: "#f97316" },
  MEDIUM: { color: "text-yellow-500", border: "border-yellow-500/30", bg: "bg-yellow-500/10", hex: "#eab308" },
  LOW: { color: "text-amber-500", border: "border-amber-500/30", bg: "bg-amber-500/10", hex: "#f59e0b" },
  SAFE: { color: "text-teal-400", border: "border-teal-400/30", bg: "bg-teal-400/10", hex: "#2dd4bf" },
};
